services:
  api-gateway:
    image: api-gateway
    build:
      context: "./apiGateway"
      dockerfile: "../api-gateway.Dockerfile"
    ports:
      - "80:8080" # Tylko Gateway jest wystawiony na zewnątrz (na hosta)
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
    networks:
      - frontend-network
      - backend-network
    restart: unless-stopped

  frontend:
    image: frontend:secure
    build:
      context: "./frontend" 
      dockerfile: "../frontend.Dockerfile"
    networks:
      - frontend-network # Frontend nie ma pojęcia o istnieniu bazy danych czy redisa
    restart: unless-stopped

  backend:
    image: backend
    build:
      context: "./project"
      dockerfile: "../backend.Dockerfile"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy # Backend potrzebuje Redisa, więc musi na niego poczekać
    networks:
      - frontend-network # Odbiera ruch od API Gateway
      - backend-network  # Wysyła zapytania do DB i Redisa
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - backend-network # Ukryty w prywatnej sieci
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  db:
    image: db
    build:
      context: "./Database"
      dockerfile: "../database.Dockerfile"
    env_file:
      - "./Database/.env"
    networks:
      - backend-network # Ukryty w prywatnej sieci
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
    internal: true

volumes:
  db-data: