services:
  frontend:
    image: frontend:secure
    build:
      context: "./frontend" 
      dockerfile: "../frontend.Dockerfile"
    ports:
      - "80:8080" # Przekierowujemy port 80 z hosta na bezpieczny port 8080 w kontenerze
    depends_on:
      - backend
  backend:
    image: backend
    build:
      context: "./project"
      dockerfile: "../backend.Dockerfile"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
#    networks:
#        - app-network
  db:
    image: db
    build:
      context: "./Database"
      dockerfile: "../database.Dockerfile"
    ports:
      - "3306:3306"
    env_file:
        - "./Database/.env"
#    networks:
#      - app-network
    volumes:
        - db-data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5
#networks:
#  app-network:
#    driver: bridge

volumes:
  db-data: