spring.application.name=project
application-description=This is the Music Browser API
application-version=1.0.0
# link do swaggera
# http://localhost:8080/swagger-ui/index.html
spring.datasource.url=jdbc:mysql://db:3306/mydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root_pass
server.port=8080
server.address=0.0.0.0
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl.auto=update

security.jwt.secret-key=7913c99e3e5d5b73e32fb11fa08bb29d91fcc5d284c55bc948232bb6405fa2f1
security.jwt.expiration-time=3600000

#pepper
security.pepper=1sdf3sdf4sdf5sdf6sdf7sdf8sdf9sdf0sdf

